Russian lang
reactjs/ru.reactjs.org pull request #703
Opened 2021-12-23 11:14 UTC by revidovich

понятный!

**Если ваш пулреквест является исправлением бага, а не переводом, то сперва убедитесь, что проблема относится ТОЛЬКО к https://ru.reactjs.org, а не к https://reactjs.org.** Если это не так, то пулреквест следует открыть в родительском репозитории.

2022-03-26 11:14 UTC, ntishkevich requested changes

2022-03-26 11:14 UTC, ntishkevich commented on content/docs/reconciliation.md
> +При построении нового дерева, новые DOM-узлы вставляются в DOM. Экземпляры компонента получают `UNSAFE_componentWillMount()`, а затем `componentDidMount()`. Любое состояние, связанное со старым дерев
Просьба, пожалуйста, не разносите предложения на несколько строк, если в оригинале было в одной строчке, из-за этого при синхронизации изменений из репозитория `reactjs.org` с нашим репозиторием будут постоянно возникать конфликты.
```suggestion
При уничтожении дерева старые DOM-узлы удаляются, а экземпляры компонента получают `componentWillUnmount()`. При построении нового дерева, новые DOM-узлы вставляются в DOM. Экземпляры компонента получают `UNSAFE_componentWillMount()`, а затем `componentDidMount()`. Любое состояние, связанное со старым деревом, теряется.
```

2022-03-26 11:14 UTC, ntishkevich commented on content/docs/reconciliation.md
> +При этом старый `Counter` уничтожится, смонтируется новый.
Я бы убрал в таком случае запятую и использовал бы для соединения двух частей `и`
```suggestion
При этом старый `Counter` уничтожится и смонтируется новый.
```

2022-03-26 11:14 UTC, ntishkevich commented on content/docs/reconciliation.md
> +Когда уникальное значение отсутствует, вы можете добавить новое свойство идентификатора в вашу модель, либо прохешировать данные, чтобы сгенерировать ключ. Ключ должен быть уникальным только среди ег
На мой взгляд, все же лучше оставить `или`, упрощает само предложение и уменьшает кол-во запятых, который могут визуально путать, ожидая, что еще будет часть с `либо`.
```suggestion
Когда уникальное значение отсутствует, вы можете добавить новое свойство идентификатора в вашу модель или прохешировать данные, чтобы сгенерировать ключ. Ключ должен быть уникальным только среди его соседей, а не глобально.
```

2022-03-26 11:14 UTC, ntishkevich commented on content/docs/reconciliation.md
> +Важно помнить, что алгоритм согласования — это деталь реализации. React может повторно рендерить всё приложение на каждое действие, конечный результат будет тем же. Для ясности, повторный рендер в эт
Я предлагаю заменить слово `здесь` на статью, так как не совсем понятно где "здесь"?

```suggestion
Важно помнить, что алгоритм согласования — это деталь реализации. React может повторно рендерить всё приложение на каждое действие, конечный результат будет тем же. Для ясности, повторный рендер в этом контексте означает вызов функции `render` для всех компонентов, но это не означает, что React размонтирует и смонтирует их заново. Он лишь применит различия, следуя правилам, которые были обозначены в статье выше.
```

2022-07-16 04:01 UTC, revidovich commented on content/docs/reconciliation.md
> +Мы регулярно совершенствуем эвристический подход, чтобы ускорить производительность. В текущей реализации вы можете выразить факт того, что поддерево было перемещено среди своих соседей, но вы не мож
Боже, мой вариант не лучше актуального..... можно оставить только "но вы не можете сказать, что оно переместилось", остальное так же на тарабарском, + нужно лезть в словарь за словом "эвристика", а "совершенствуем подходы к разработке" будет неточным переводом. ничего не получилось, можно закрывать этот мр (((

2023-01-22 18:30 UTC, closed without merging