Update translation for Strict mode
reactjs/ru.reactjs.org pull request #753
Opened 2022-06-05 14:50 UTC by romadryud

Добавление перевода для обновлённой части страницы о Strict Mode.
Ссылка на EN версию: [Link](https://reactjs.org/docs/strict-mode.html#ensuring-reusable-state).

2022-06-07 13:15 UTC, romadryud commented
@ntishkevich Можешь глянуть этот пр ? Спасибо.

2022-06-07 13:20 UTC, ntishkevich commented
> @ntishkevich Можешь глянуть этот пр ? Спасибо.
> 

Постараюсь в течении этой недели посмотреть.

2022-06-20 18:54 UTC, romadryud commented
@ntishkevich Gently ping 🏓

2022-07-01 15:08 UTC, ntishkevich commented
@romadryud мэйн ветка была обновлена, заберите последние изменения к себе в ветку.

2022-07-01 15:27 UTC, romadryud commented
@ntishkevich Сделано ✅

2022-07-08 19:20 UTC, ntishkevich requested changes
Спасибо за ваш перевод. Небольшие замечания и думаю, что можно мержить.

2022-07-08 19:20 UTC, ntishkevich commented on content/docs/strict-mode.md
> +В будущем мы хотели бы добавить функцию, которая позволяет React добавлять и удалять разделы пользовательского интерфейса с сохранением состояния. Например, когда пользователь переходит от экрана к э
Перед "Для" пропущен пробел.
```suggestion
В будущем мы хотели бы добавить функцию, которая позволяет React добавлять и удалять разделы пользовательского интерфейса с сохранением состояния. Например, когда пользователь переходит от экрана к экрану и обратно, React должен иметь возможность немедленно отображать предыдущий экран. Для этого React поддерживает повторное монтирование деревьев с использованием того же состояния компонента, которое использовалось до размонтирования.
```

2022-07-08 19:20 UTC, ntishkevich commented on content/docs/strict-mode.md
> +Чтобы помочь устранить эти проблемы, React 18 представляет новую проверку только для разработки в строгом режиме. Эта новая проверка автоматически размонтирует и перемонтирует каждый компонент всякий
`development-only` я бы перевел в данном случае как "только в режиме разработки". Просто "разработка" осит довольно расплывчатый смысл: разработка сайта или режим разработки.

2022-07-08 19:20 UTC, ntishkevich commented on content/docs/strict-mode.md
> +> Это относится только к режиму разработки, _производственное поведение остается неизменным_.
Здесь я бы production переводил бы как "продакшен", так как "производственное поведение" очень непонятно о чем идёт речь. Можно попробовать еще `для продакшена поведение остаётся неизменным".

Также замените букву `е` на `ё` в слове `остаётся`.

2022-07-08 19:20 UTC, ntishkevich commented on content/docs/strict-mode.md
> +Для получения помощи в решении распространенных проблем см.:
Замените букву `е` на `ё` в слове `распространённых`.

2022-07-13 16:39 UTC, romadryud commented
@ntishkevich Спасибо за ревью, сделал правки, просмотрите ещё раз и думаю что можно мержить :)

2022-07-14 09:34 UTC, ntishkevich approved these changes

2022-07-14 09:37 UTC, merged