Update info about hooks and react-dom
reactjs/ru.reactjs.org pull request #757
Opened 2022-06-17 17:12 UTC by jkorichneva

Добрый день,
- изменила версию в ссылках на cdn с 17 на 18ю
- привела страницу ReactDOM в аналогичное состояние с [EN-версией](https://reactjs.org/docs/react-dom.html)
- добавила информацию на страницу справочника хуков про обновления в 18й версии
![Capture2](https://user-images.githubusercontent.com/26360334/174346064-af8dc875-1c57-4127-9c60-10f9739d745f.PNG)
![Capture44](https://user-images.githubusercontent.com/26360334/174346070-0d096602-e7cf-4858-8d1d-6c8a46964310.PNG)
![Capture](https://user-images.githubusercontent.com/26360334/174346073-818e6c84-803b-43c8-9747-87bc77619640.PNG)

2022-06-22 08:25 UTC, ntishkevich commented
@jkorichneva хорошо, но пока ревью ваших изменений зависнет из-за разрешения конфликтов с ПР-ами для синхронизации контента с английской документацией. После разрешения, я смогу проревьювить. Надеюсь на понимание.

2022-06-22 16:44 UTC, jkorichneva commented
@ntishkevich да, конечно. Могу помочь как-то с разрешением конфликтов?

2022-06-23 08:16 UTC, ntishkevich commented
> @ntishkevich да, конечно. Могу помочь как-то с разрешением конфликтов?

благодарю за предложение, но ничего не нужно 😄

2022-07-02 07:00 UTC, jkorichneva commented
@ntishkevich обновила

2022-07-08 19:10 UTC, ntishkevich requested changes
Спасибо за ваш перевод. Есть несколько небольших замечаний.

2022-07-08 19:10 UTC, ntishkevich commented on content/docs/reference-react-dom.md
> +> `flushSync` может вызывать ожидающие эффекты и синхронно выполнять их обновления, не дожидаясь ответа.
Немного потерян смысл, как мне кажется, `returning` больше ближе к переводу "возврат", попробуйте переформулировать и может лучше подобрать перевод.

2022-07-08 19:10 UTC, ntishkevich commented on content/docs/reference-react-dom.md
> +> `flushSync` может вынуждать ожидающие ответа Suspense отображать их `fallback` состояние.
Получился какой-то машинный перевод и потерялся смысл. Попробуйте  еще раз перевести иначе, обратите внимание, что Suspense не даёт ответа, а дожидается отображения содержимого, а до этих пор показывает `fallback`

2022-07-08 19:10 UTC, ntishkevich commented on content/docs/reference-react-dom.md
> +> Методы `render` и `hydrate` были заменены на новые [client методы](https://reactjs.org/docs/react-dom-client.html) в React 18. Эти методы будут предупреждать, что ваше приложение будет работать, ка
Я бы переформулировал слова "ваше приложение будет работать, словно используется версия React 17"

2022-07-16 14:52 UTC, jkorichneva commented on content/docs/reference-react-dom.md
> +> Методы `render` и `hydrate` были заменены на новые [client методы](https://reactjs.org/docs/react-dom-client.html) в React 18. Эти методы будут предупреждать, что ваше приложение будет работать, ка
поправила

2022-07-16 14:53 UTC, jkorichneva commented on content/docs/reference-react-dom.md
> +> `flushSync` может вызывать ожидающие эффекты и синхронно выполнять их обновления, не дожидаясь ответа.
переформулировала

2022-07-16 14:53 UTC, jkorichneva commented on content/docs/reference-react-dom.md
> +> `flushSync` может вынуждать ожидающие ответа Suspense отображать их `fallback` состояние.
переформулировала

2023-01-22 19:50 UTC, ntishkevich approved these changes

2023-01-22 19:50 UTC, merged