Translate passing data deeply with context
reactjs/ru.reactjs.org pull request #973
Opened 2024-09-26 11:20 UTC by Pyplee

2024-11-13 16:02 UTC, titovmx requested changes
Спасибо за перевод! Оставил несколько предложений

2024-11-29 17:04 UTC, Pyplee commented on src/content/learn/passing-data-deeply-with-context.md
> +- Что такое "проп бурение"
Я посмотрел, и правда, зачастую разработчики пишут prop drilling, иногда проставляя рядом название явления на Русском. Я исправил этот недочет. 

Я поставил ("prop drilling" (бурение пропсов)) в раздел - вы узнаете\выучите (13 строка), принял исправление на 35 (написал просто "Бурение пропсов") и поставил полноценное расшифрование ("prop drilling" (бурение пропсов)) на 880 строке т.к она является заголовком в челленджах, думаю не будет лишним.

2024-11-29 17:04 UTC, Pyplee commented on src/content/learn/passing-data-deeply-with-context.md
>  <Diagram name="passing_data_lifting_state" height={160} width={608} captionPosition="top" alt="Diagram with a tree of three components. The parent contains a bubble representing a value highlighted i
Сделал

2024-11-29 17:08 UTC, Pyplee commented
Заметки внес, поправил некоторые моменты, прошу проревьюрить перевод.

2025-05-12 16:06 UTC, dimatitov commented
👋 @Pyplee, спасибо за проделанную работу!

Вижу, что в PR сейчас есть конфликты — потребуется их разрешить, чтобы можно было продолжить.

@titovmx, когда будет возможность, посмотри, пожалуйста, актуальное состояние — возможно, после разрешения конфликтов PR уже готов к мержу.

2025-12-04 18:26 UTC, closed without merging